on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - main

name: Continuous Deployment

concurrency:
  group: "release"
  cancel-in-progress: false

jobs:
  build:
    uses: ./.github/workflows/ci.yaml
    secrets: inherit

  release-please:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - uses: googleapis/release-please-action@v5
        id: release

    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}

  publish-npm:
    runs-on: ubuntu-latest

    if: ${{ fromJson(needs.release-please.outputs.releases_created) }}
    needs:
      - build
      - release-please

    environment:
      name: npm
      url: https://www.npmjs.com/package/@cprecioso/paseo-worktreeinclude

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-repo

      - uses: actions/download-artifact@v8
        with:
          name: package.tgz

      - run: npm publish package.tgz
